const { PrismaClient } = require('@prisma/client');
const fs = require('fs');

const prisma = new PrismaClient();

async function exportToSQL() {
  try {
    console.log('🔄 Fetching data from database...');
    
    // Fetch all data
    const users = await prisma.user.findMany();
    const incidents = await prisma.incident.findMany();
    
    console.log(`📊 Found ${users.length} users and ${incidents.length} incidents`);
    
    let sql = '-- Database dump generated by Prisma export script\n';
    sql += `-- Generated at: ${new Date().toISOString()}\n\n`;
    
    // Create tables
    sql += '-- Table structure for User\n';
    sql += 'CREATE TABLE IF NOT EXISTS "User" (\n';
    sql += '  "id" TEXT PRIMARY KEY,\n';
    sql += '  "email" TEXT UNIQUE NOT NULL,\n';
    sql += '  "password" TEXT NOT NULL,\n';
    sql += '  "name" TEXT,\n';
    sql += '  "firstName" TEXT,\n';
    sql += '  "lastName" TEXT,\n';
    sql += '  "role" TEXT DEFAULT \'USER\',\n';
    sql += '  "createdAt" TIMESTAMP DEFAULT NOW(),\n';
    sql += '  "updatedAt" TIMESTAMP DEFAULT NOW()\n';
    sql += ');\n\n';
    
    sql += '-- Table structure for Incident\n';
    sql += 'CREATE TABLE IF NOT EXISTS "Incident" (\n';
    sql += '  "id" TEXT PRIMARY KEY,\n';
    sql += '  "createdAt" TIMESTAMP DEFAULT NOW(),\n';
    sql += '  "type" TEXT NOT NULL,\n';
    sql += '  "description" TEXT NOT NULL,\n';
    sql += '  "location" TEXT NOT NULL,\n';
    sql += '  "status" TEXT DEFAULT \'REPORTED\',\n';
    sql += '  "photoUrl" TEXT,\n';
    sql += '  "userId" TEXT NOT NULL,\n';
    sql += '  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE\n';
    sql += ');\n\n';
    
    // Insert users
    if (users.length > 0) {
      sql += '-- Data for User table\n';
      for (const user of users) {
        const values = [
          escape(user.id),
          escape(user.email),
          escape(user.password),
          user.name ? escape(user.name) : 'NULL',
          user.firstName ? escape(user.firstName) : 'NULL',
          user.lastName ? escape(user.lastName) : 'NULL',
          escape(user.role),
          `'${user.createdAt.toISOString()}'`,
          `'${user.updatedAt.toISOString()}'`
        ];
        sql += `INSERT INTO "User" ("id", "email", "password", "name", "firstName", "lastName", "role", "createdAt", "updatedAt") VALUES (${values.join(', ')});\n`;
      }
      sql += '\n';
    }
    
    // Insert incidents
    if (incidents.length > 0) {
      sql += '-- Data for Incident table\n';
      for (const incident of incidents) {
        const values = [
          escape(incident.id),
          `'${incident.createdAt.toISOString()}'`,
          escape(incident.type),
          escape(incident.description),
          escape(incident.location),
          escape(incident.status),
          incident.photoUrl ? escape(incident.photoUrl) : 'NULL',
          escape(incident.userId)
        ];
        sql += `INSERT INTO "Incident" ("id", "createdAt", "type", "description", "location", "status", "photoUrl", "userId") VALUES (${values.join(', ')});\n`;
      }
      sql += '\n';
    }
    
    // Write to file
    fs.writeFileSync('dump.sql', sql);
    console.log('✅ SQL dump created successfully: dump.sql');
    
  } catch (error) {
    console.error('❌ Error exporting data:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

function escape(str) {
  if (str === null || str === undefined) return 'NULL';
  return `'${String(str).replace(/'/g, "''")}'`;
}

exportToSQL();
